### ISSUE TITLE
allow to specify the instrument instruction set

### ISSUE THREAD

**Issue by srgblnch** [srgblnch/skippy#36]
It has been received a request to allow the skippy to use an specific file with the instruction set, without the use of "*IDN?" command.

This has to be implemented thinking also with the watchdog, because it uses this command to check it is alive. So if the user of this feature, uses it against an instrument that doesn't answer to idn, the watchdog will fail.

**Comment by mliszcz** [comment]
Hi Sergi,

We need such a feature at S2Innovation for Kepco BOP (which is not supported by default instruction sets). Do you plan to work on this issue in the near future? If no, we can help with development and submit a PR.

Thanks!

**Comment by srgblnch** [comment]
I've implemented something that may help you. There is a new [tag 1.6.0-alpha1](https://github.com/srgblnch/skippy/releases/tag/1.6.0-alpha1) with what you have two newer optional properties.
* AvoidIDN: a Boolean (default false) to force the device behavior to not identify the instrument. So then it doesn't load any set of instructions, neither have the watchdog feature.
* InstructionsFile: a string with a full path to where the skippy can find a file with the instructions set to load

This two features together may fit with your request?

You have another property available that could avoid the second mentioned. There is the "DynamicAttributes" that, with the same syntax used in the files to be loaded (by now only the attribute builder) you can store it in the tango database as a property.

**Comment by mliszcz** [comment]
Thanks a lot for working on this! As we discussed on slack, I'd like to use a custom file and still have watchdog enabled. So I don't want to set 'AvoidIDN'. I've submitted a PR with this change:
https://github.com/srgblnch/skippy/pull/50. Please review when you find some time.
